(defun color-theme-stesen ()
  (interactive)
  (color-theme-install
   '(color-theme-stesen
      ((background-color . "#1c1c1c")
      (background-mode . light)
      (border-color . "#1c1c1c")
      (cursor-color . "#f0670a")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#1c1c1c"))))
     (mode-line ((t (:foreground "#000000" :background "#ffffff"))))
     (region ((t (:background "#434d0f"))))
     (font-lock-builtin-face ((t (:foreground "#659cd7"))))
     (font-lock-comment-face ((t (:foreground "#5e5e5e"))))
     (font-lock-function-name-face ((t (:foreground "#e6db8f"))))
     (font-lock-keyword-face ((t (:foreground "#5f8db4"))))
     (font-lock-string-face ((t (:foreground "#ff70de"))))
     (font-lock-type-face ((t (:foreground"#b2ff66"))))
     (font-lock-constant-face ((t (:foreground "#ff762e"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#9f5cff" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-stesen)