(defun color-theme-stesen-light ()
  (interactive)
  (color-theme-install
   '(color-theme-stesen-light
      ((background-color . "#fffff0")
      (background-mode . light)
      (border-color . "#fffff0")
      (cursor-color . "#000000")
      (foreground-color . "#000000")
      (mouse-color . "black"))
     (fringe ((t (:background "#fffff0"))))
     (mode-line ((t (:foreground "#ffffff" :background "#2b2b2b"))))
     (region ((t (:background "#9e9e9e"))))
     (font-lock-builtin-face ((t (:foreground "#f820b4"))))
     (font-lock-comment-face ((t (:foreground "#7d827d"))))
     (font-lock-function-name-face ((t (:foreground "#102cc1" :bold t))))
     (font-lock-keyword-face ((t (:foreground "#1590e0"))))
     (font-lock-string-face ((t (:foreground "#c77429"))))
     (font-lock-type-face ((t (:foreground"#199915"))))
     (font-lock-constant-face ((t (:foreground "#8a5d00"))))
     (font-lock-variable-name-face ((t (:foreground "#ad7500"))))
     (minibuffer-prompt ((t (:foreground "#163ea7" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'color-theme-stesen-light)